// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for ios - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCYAuWWyAtuMFmMhAXamE62lTzqCOGyIxk',
    appId: '1:498037161519:web:96fffb2fee43367433d0da',
    messagingSenderId: '498037161519',
    projectId: 'miappmovil2',
    authDomain: 'miappmovil2.firebaseapp.com',
    storageBucket: 'miappmovil2.firebasestorage.app',
    measurementId: 'G-HNCGY04SF1',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAMlFEX-2OnOihwSkShaakyhPteduy9YeI',
    appId: '1:498037161519:android:bfbe4258c5b65e1f33d0da',
    messagingSenderId: '498037161519',
    projectId: 'miappmovil2',
    storageBucket: 'miappmovil2.firebasestorage.app',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCYAuWWyAtuMFmMhAXamE62lTzqCOGyIxk',
    appId: '1:498037161519:web:2ee508dde7fdb08633d0da',
    messagingSenderId: '498037161519',
    projectId: 'miappmovil2',
    authDomain: 'miappmovil2.firebaseapp.com',
    storageBucket: 'miappmovil2.firebasestorage.app',
    measurementId: 'G-W0JK3QH9YX',
  );
}
